START_PASSWORD_VALIDATOR_CONTROLLER = "Start end point /validate-password"
END_PASSWORD_VALIDATOR_CONTROLLER = "End point /validate-password successfully executed"
PASSWORD_FIELD_NOT_EXISTS = "Password field is required!"
PASSWORD_FIELD_NULL = "Password value can't be null!"
PASSWORD_PAYLOAD_VALID = "Password payload is valid"
BAD_REQUEST = "Bad Request"
METHOD_NOT_ALLOWED = "Method Not Allowed"
INTERNAL_SERVER_ERROR = "Internal Server Error"
INTERNAL_SERVER_ERROR_MESSAGE = "Sorry, it's me, not you. let me try again!"
FACTORY_PASSWORD_RULE_DEFAULT = "Default password rule class created in factory"
VALIDATION_PASSWORD_USE_CASE_BEGIN = "Start use case process for validate password = "
VALIDATION_PASSWORD_USE_CASE_END = "Use case process for validate password successfully executed with response = "
VALIDATION_PASSWORD_DEFAULT = "Start default rules for validation for password"
VALIDATION_PASSWORD_DEFAULT_OK = "Password is valid"
FORMAT_PASSWORD = "Password String trim"
VALIDATING_PASSWORD_SIZE = "Validating password size"
VALID_PASSWORD_SIZE = "Validation ok - Password size is valid"
INVALID_PASSWORD_SIZE = "Invalid password size, password must be greater than 8 characters!"
INVALID_PASSWORD_NO_NUMBER = "Invalid password format, password must contain at least one numeric character!"
VALIDATING_PASSWORD_NUMBER = "Validating if password contains numeric character"
VALID_PASSWORD_NUMBER = "Validation ok - Password contains numeric character"
INVALID_PASSWORD_NO_UPPER = "Invalid password format, password must contain at least one upper case character!"
VALIDATING_PASSWORD_UPPER = "Validating if password contains upper case character"
VALID_PASSWORD_UPPER = "Validation ok - Password contains upper character"
INVALID_PASSWORD_NO_LOWER = "Invalid password format, password must contain at least one lower case character!"
VALIDATING_PASSWORD_LOWER = "Validating if password contains lower case character"
VALID_PASSWORD_LOWER = "Validation ok - Password contains lower character"
INVALID_PASSWORD_NO_SPECIAL_CHAR = "Invalid password format, password must contain at least one special " \
                                   "character(!@#$%^&*()+-)!"
VALIDATING_PASSWORD_SPECIAL_CHAR = "Validating if password contains special character"
VALID_PASSWORD_SPECIAL_CHAR = "Validation ok - Password contains special character"
VALIDATING_PASSWORD_BLANK_CHAR = "Validating if password contains not contains blank character"
VALID_PASSWORD_BLANK_CHAR = "Validation ok - Password not contains blank character"
INVALID_PASSWORD_CONTAINS_BLANK_CHAR = "Invalid password format, password can't contains blank character"
INVALID_PASSWORD_NO_DUPLICATED_CHAR = "Invalid password format, password contains repeated characters!"
VALIDATING_PASSWORD_DUPLICATED_CHAR = "Validating if password contains repeated characters"
VALID_PASSWORD_NOT_DUPLICATED_CHAR = "Validation ok - Password not contains repeated characters"
